### ISSUE TITLE
How to use it in swift?

### ISSUE THREAD

**Issue by etamity** [xmartlabs/XLSlidingContainer#1]
Hi , 
I am trying to use it in swift, but I got the error when I trying to embedded a view controller:

class PAPRecordViewController:UIViewController, XLSlidingContainerViewController{

I am getting compile error:
 multiple inheritance from classes swift

Please help. Thanks

**Comment by mats-claassen** [comment]
Thanks for mentioning it. I will look into it when I have some time

**Comment by mats-claassen** [comment]
In swift you cannot inherit from two classes.
I will soon upload a Swift example.

**Comment by mats-claassen** [comment]
The issue was because the protocol and the class had the same name. It is now fixed and there is a Swift example as well
